### ISSUE TITLE
Grafana: Upgrading grafana-experimental to 1.6 (or 1.5) breaks components using EditorList

### ISSUE THREAD

**Issue by matyax** [grafana/grafana-experimental#68]
As part of the data sources configuration pages refactor, I needed to upgrade the dependency to migrate `DatasourceHTTPSettings` to `ConnectionSettings`, `AdvancedHttpSettings`, and `Auth`, but after the upgrade it break every place where `EditorList` was used.

It seems that [this change](https://github.com/grafana/grafana-experimental/commit/480e1aa0131542a595a45d66d3ae1282e077d514) broke backwards compatibility in Grafana.

Affected components:

```
public/app/features/plugins/sql/components/visual-query-builder/GroupByRow.tsx
public/app/plugins/datasource/azuremonitor/components/MetricsQueryEditor/DimensionFields.tsx
public/app/plugins/datasource/azuremonitor/components/TracesQueryEditor/Filters.tsx
public/app/plugins/datasource/cloud-monitoring/components/LabelFilter.tsx
public/app/plugins/datasource/cloudwatch/components/Dimensions/Dimensions.tsx
public/app/plugins/datasource/cloudwatch/components/SQLBuilderEditor/SQLFilter.tsx
public/app/plugins/datasource/cloudwatch/components/SQLBuilderEditor/SQLGroupBy.tsx
public/app/plugins/datasource/cloudwatch/components/VariableQueryEditor/MultiFilter.tsx
public/app/plugins/datasource/mssql/sqlCompletionProvider.ts
public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.tsx
public/app/plugins/datasource/prometheus/querybuilder/shared/LabelFilters.tsx
```

**Comment by sasklacz** [comment]
cc @zoltanbedi @jackw

**Comment by mdvictor** [comment]
This should be fixed soon by this [PR](https://github.com/grafana/grafana-experimental/pull/69)

**Comment by sasklacz** [comment]
@matyax can you close this one once it's confirmed Victor's PR fixed the issue ?

**Comment by matyax** [comment]
Sure thing.

**Comment by matyax** [comment]
The new version has been released so I'll be testing this soon.

**Comment by matyax** [comment]
I just upgraded in Grafana to 1.6.1 and there are no type issues and I see the required components. Thanks a lot everyone!

**Comment by joey-grafana** [comment]
There seems to be a different issue in `grafana/public/app/plugins/datasource/mssql/sqlCompletionProvider.ts` when upgrading to 1.6.2.

![Screenshot 2023-07-24 at 13 19 12](https://github.com/grafana/grafana-experimental/assets/90795735/1b18fdc5-7a0d-462d-a81c-bdf016019f0a)
![Screenshot 2023-07-24 at 13 23 10](https://github.com/grafana/grafana-experimental/assets/90795735/fdbea017-fbef-46b9-9540-6d187c3343b8)

**Comment by mdvictor** [comment]
I'm looking into this right away

**Comment by jackw** [comment]
FYI - I updated the [experimental PR](https://github.com/grafana/grafana/pull/68681) here to cater for that. If that was wrong of me then we can revert it in that PR.

**Comment by mdvictor** [comment]
@jackw Thanks for linking this and updating the file. I approved your PR!
